#!/usr/bin/env bash
#
# Sync GitHub Discussions reactions into _data/reactions.yml.
#
#   1. ensure every published entry has a Discussion (title == the entry's URL path)
#   2. lock new Discussions, so they take reactions but not comments
#   3. write the reaction counts out as Jekyll data
#
# Reads the entry inventory from the built _site/index.json, which already lists
# every entry with its url, uid, title and collection.
#
# Requires: gh, jq. Both are preinstalled on GitHub-hosted runners.
# Requires GITHUB_TOKEN with `discussions: write`.

set -euo pipefail

REPO="${GITHUB_REPOSITORY:-gpai-wiki/gpai-wiki.github.io}"
OWNER="${REPO%%/*}"
NAME="${REPO##*/}"
CATEGORY="${DISCUSSION_CATEGORY:-Entries}"
INDEX="${1:-_site/index.json}"
OUT="${2:-_data/reactions.yml}"
SITE_URL="${SITE_URL:-https://gpai-wiki.github.io}"

[ -f "$INDEX" ] || { echo "no $INDEX -- build the site first" >&2; exit 1; }

# ---- repository + category ids ---------------------------------------------
read -r REPO_ID CAT_ID < <(
  gh api graphql -f owner="$OWNER" -f name="$NAME" -f query='
    query($owner:String!, $name:String!) {
      repository(owner:$owner, name:$name) {
        id
        discussionCategories(first:50) { nodes { id name } }
      }
    }' --jq "[.data.repository.id,
              (.data.repository.discussionCategories.nodes[]
               | select(.name == \"$CATEGORY\") | .id)] | @tsv"
)

if [ -z "${CAT_ID:-}" ]; then
  echo "Discussions category '$CATEGORY' not found." >&2
  echo "Enable Discussions on $REPO and create that category first." >&2
  exit 1
fi

# ---- existing discussions ---------------------------------------------------
fetch_discussions() {
  local cursor="null" page
  : > /tmp/discussions.jsonl
  while :; do
    page=$(gh api graphql -f owner="$OWNER" -f name="$NAME" \
      -F cursor="$cursor" -f query='
      query($owner:String!, $name:String!, $cursor:String) {
        repository(owner:$owner, name:$name) {
          discussions(first:100, after:$cursor) {
            pageInfo { hasNextPage endCursor }
            nodes {
              id number title url locked
              reactionGroups { content reactors { totalCount } }
            }
          }
        }
      }')
    echo "$page" | jq -c '.data.repository.discussions.nodes[]' >> /tmp/discussions.jsonl
    [ "$(echo "$page" | jq -r '.data.repository.discussions.pageInfo.hasNextPage')" = "true" ] || break
    cursor=$(echo "$page" | jq -r '.data.repository.discussions.pageInfo.endCursor')
  done
}

fetch_discussions
echo "existing discussions: $(wc -l < /tmp/discussions.jsonl | tr -d ' ')"

# ---- create one per entry that lacks it ------------------------------------
created=0
while IFS=$'\t' read -r path title uid; do
  [ -n "$path" ] || continue
  if jq -e --arg t "$path" 'select(.title == $t)' /tmp/discussions.jsonl >/dev/null 2>&1; then
    continue
  fi
  body=$(printf 'Reactions for **%s** on the GPAI Wiki.\n\n%s%s\n\n_Opened automatically. Locked: react here, discuss in a pull request._' \
                "${title//\"/}" "$SITE_URL" "$path")
  new_id=$(gh api graphql -f repoId="$REPO_ID" -f catId="$CAT_ID" \
    -f title="$path" -f body="$body" -f query='
    mutation($repoId:ID!, $catId:ID!, $title:String!, $body:String!) {
      createDiscussion(input:{repositoryId:$repoId, categoryId:$catId, title:$title, body:$body}) {
        discussion { id url }
      }
    }' --jq '.data.createDiscussion.discussion.id')

  # Locked discussions still accept reactions; they refuse new comments.
  gh api graphql -f id="$new_id" -f query='
    mutation($id:ID!) { lockLockable(input:{lockableId:$id}) { clientMutationId } }' >/dev/null

  echo "  created + locked  $path"
  created=$((created + 1))
done < <(jq -r '.items[] | [(.url | sub("^https?://[^/]+"; "")), .title, .uid] | @tsv' "$INDEX")

echo "created: $created"
[ "$created" -gt 0 ] && fetch_discussions

# ---- write the data file ----------------------------------------------------
mkdir -p "$(dirname "$OUT")"
{
  echo "# Generated by scripts/reactions.sh -- do not edit by hand."
  echo "generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "entries:"
  jq -rs '
    def count($c): (.reactionGroups[] | select(.content == $c) | .reactors.totalCount) // 0;
    sort_by(.title)[]
    | . as $d
    | {
        path: .title,
        url: .url,
        up:    count("THUMBS_UP"),
        heart: count("HEART"),
        tada:  count("HOORAY"),
        rocket:count("ROCKET"),
        eyes:  count("EYES"),
        laugh: count("LAUGH"),
        down:  count("THUMBS_DOWN"),
        conf:  count("CONFUSED")
      }
    | .positive = (.up + .heart + .tada + .rocket)
    | .total    = (.positive + .eyes + .laugh + .down + .conf)
    | select(.path | startswith("/"))
    | "  \"\(.path)\":\n" +
      "    url: \(.url)\n" +
      "    positive: \(.positive)\n" +
      "    total: \(.total)\n" +
      "    up: \(.up)\n    heart: \(.heart)\n    tada: \(.tada)\n    rocket: \(.rocket)\n" +
      "    eyes: \(.eyes)\n    laugh: \(.laugh)\n    down: \(.down)\n    conf: \(.conf)"
  ' /tmp/discussions.jsonl
} > "$OUT"

echo "wrote $OUT"
